//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT2_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatDBEntities1 : DbContext
    {
        public ChatDBEntities1()
            : base("name=ChatDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<ChatMsg> ChatMsg { get; set; }
        public virtual DbSet<ChatMsg_TimeLimited> ChatMsg_TimeLimited { get; set; }
        public virtual DbSet<PermanentAccount> PermanentAccount { get; set; }
        public virtual DbSet<TemporaryAccount> TemporaryAccount { get; set; }
    }
}
